/**
 * @format
 * @description Automatically generated by the command line vue-gen-router
 * @update Thu Aug 08 2019 21:13:14 GMT+0800 (GMT+08:00)
 */

import { RouteConfig } from 'vue-router';

// @ts-ignore
import Routerview from 'components/Routerview';
// @ts-ignore
import Layout from 'views/layout/Layout';

export const routerConfig: RouteConfig[] = [
  {
    path: '/login',
    name: 'login',
    component: {
      render: () => <router-view />
    },
    props: true,
    meta: {
      title: '系统',
      index: true,
      auth: [
        'architecture',
        'subject',
        'department',
        'class',
        'teacherFile',
        'studentFile',
        'parentFile',
        'role',
        'term'
      ]
    }
  },
  {
    path: '',
    name: 'Layout',
    redirect: '/index',
    component: Layout,
    meta: { title: '架构', auth: ['architecture'] },
    children: [
      {
        path: '/index',
        component: Routerview,
        meta: {
          title: '首页',
          index: true,
          icon: 'icon-shouyex',
          auth: ['indexview', 'campusInfo']
        },
        children: [
          {
            path: '',
            name: 'indexview',
            // prettier-ignore
            // @ts-ignore
            component: () => import('views/index/index'),
            meta: { title: '首页', index: true, auth: ['indexview'] }
          },
          {
            path: 'edit',
            name: 'indexedit',
            // prettier-ignore
            // @ts-ignore
            component: () => import('views/index/edit'),
            meta: { title: '编辑', auth: ['campusInfo'] }
          }
        ]
      },
      {
        path: '/notice',
        name: 'notice',
        component: {
          render: h => (
            <keep-alive include="cloudStorage">
              <router-view />
            </keep-alive>
          )
        },
        meta: {
          title: '校园通知',
          icon: 'icon-xiaoyuantongzhix',
          auth: ['notice']
        },
        children: [
          {
            path: 'list',
            name: 'noticeList',
            // prettier-ignore
            // @ts-ignore
            component: () => import('views/notice/tabIndex'),
            meta: { title: '校园通知', index: true, auth: ['notice'] }
          },
          {
            path: 'edit',
            name: 'noticeEdit',
            // prettier-ignore
            // @ts-ignore
            component: () => import('views/notice/edit'),
            meta: { title: '发送通知', auth: ['notice'] }
          },
          {
            path: 'detail',
            name: 'noticeDetail',
            // prettier-ignore
            // @ts-ignore
            component: () => import('views/notice/detail'),
            meta: { title: '详情', auth: ['notice'] }
          }
        ]
      }
    ]
  },
  {
    path: '/updateServe',
    name: 'updateServe',
    // prettier-ignore
    // @ts-ignore
    component: () => import('views/updateServe/index'),
    meta: { title: '升级服务' },
    children: [
      {
        path: 'teacher',
        name: 'teacherInSubject',
        // prettier-ignore
        // @ts-ignore
        component: () => import('views/views/viewsviews/viewsviews/viewsviews/views/views/system/archives/facultyManage'),
        meta: { title: '教职工管理', auth: ['teacherFile'] }
      }
    ]
  },
  { path: '/publish', name: 'publish', meta: { title: '工作包' } }
];
